const entities=[
  {name:"Model Context Protocol",org:"MCP ecosystem",status:"active",desc:"Protocolo abierto para conectar aplicaciones de IA con herramientas, datos y servicios.",tags:["Protocolo","Interoperabilidad","Histórico"]},
  {name:"A2A Protocol",org:"Linux Foundation ecosystem",status:"active",desc:"Interoperabilidad entre agentes con hitos de adopción registrables como evidencia histórica.",tags:["Agentes","Protocolo","Gobernanza"]},
  {name:"MCP Registry",org:"Model Context Protocol",status:"active",desc:"Primera fuente automatizada de AHI. Se captura por snapshots completos y comparación cronológica.",tags:["Registry","Snapshot","Observed"]},
  {name:"AHI Evidence Registry",org:"Agent History Index",status:"building",desc:"Ledger append-only, hashes encadenados, Merkle checkpoints y firma digital opcional.",tags:["Evidencia","SHA-256","Merkle"]},
  {name:"AHI Verification Nodes",org:"Agent History Index",status:"planned",desc:"Capa futura para ejecutar benchmarks reproducibles y distinguir lo declarado de lo verificado.",tags:["Benchmark","Latencia","Verified"]},
  {name:"Market Intelligence",org:"Agent History Index",status:"planned",desc:"Adopción, pricing, uso reportado, señales públicas y evolución de mercado con procedencia explícita.",tags:["Mercado","Traction","Pro"]}
];
const signals=[
  {type:"OBSERVATION",title:"MCP Registry bajo captura histórica",text:"AHI conserva snapshots completos y calcula diferencias entre estados sucesivos.",link:"#evidencia"},
  {type:"INTEGRITY",title:"Merkle checkpoints incorporados en V4",text:"Cada corrida de integridad puede resumir criptográficamente el ledger histórico.",link:"#evidencia"},
  {type:"ROADMAP",title:"Capability drift y risk tracking",text:"La arquitectura queda preparada para comparar capacidades, permisos, incidentes y políticas entre T0 y T1.",link:"#inteligencia"}
];
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function label(s){return {active:"ACTIVO",building:"EN CONSTRUCCIÓN",planned:"PLANIFICADO"}[s]||s.toUpperCase()}
function render(list=entities){$("#cards").innerHTML=list.map(x=>`<article class="card"><div class="card-top"><span class="badge ${x.status}">${label(x.status)}</span><span class="badge">${x.org}</span></div><h3>${x.name}</h3><p>${x.desc}</p><div class="tags">${x.tags.map(t=>`<span>${t}</span>`).join("")}</div></article>`).join("")||'<article class="card"><h3>Sin coincidencias</h3><p>Prueba otra búsqueda.</p></article>'}
function renderSignals(){$("#signals").innerHTML=signals.map(x=>`<article class="signal-item"><span>${x.type}</span><div><h3>${x.title}</h3><p>${x.text}</p></div><a href="${x.link}">Ver contexto →</a></article>`).join("")}
function search(q){q=q.trim().toLowerCase();const out=!q?entities:entities.filter(x=>[x.name,x.org,x.desc,...x.tags].join(" ").toLowerCase().includes(q));render(out);$("#explorar").scrollIntoView({behavior:"smooth"})}
$("#searchForm").addEventListener("submit",e=>{e.preventDefault();search($("#searchInput").value)});$$('[data-q]').forEach(b=>b.addEventListener('click',()=>{$('#searchInput').value=b.dataset.q;search(b.dataset.q)}));
$("#menu").addEventListener("click",()=>$("#mobileNav").classList.toggle("open"));$$('#mobileNav a').forEach(a=>a.addEventListener('click',()=>$("#mobileNav").classList.remove('open')));
function openModal(name){$(name==='pro'?'#proModal':'#contactModal').classList.add('open')}$$('[data-open]').forEach(b=>b.addEventListener('click',()=>openModal(b.dataset.open)));$$('[data-close]').forEach(b=>b.addEventListener('click',()=>b.closest('.modal').classList.remove('open')));$$('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('open')}));$$('[data-switch]').forEach(b=>b.addEventListener('click',()=>{b.closest('.modal').classList.remove('open');openModal(b.dataset.switch)}));document.addEventListener('keydown',e=>{if(e.key==='Escape')$$('.modal').forEach(m=>m.classList.remove('open'))});
async function loadStatus(){try{const r=await fetch('data/status.json',{cache:'no-store'});if(!r.ok)throw new Error('status unavailable');const d=await r.json();const s=d.latest_snapshot||{},c=d.latest_changes||{},i=d.integrity||{};$("#snapshotDate").textContent=s.date?new Date(s.date).toLocaleDateString('es-419'):"Sin snapshot local";$("#snapshotRecords").textContent=`${Number(s.records||0).toLocaleString('es-419')} registros`;const total=Number(c.added||0)+Number(c.removed||0)+Number(c.version_changes||0)+Number(c.status_changes||0)+Number(c.content_changes||0);$("#changeCount").textContent=total.toLocaleString('es-419');$("#treeSize").textContent=Number(i.tree_size||0).toLocaleString('es-419');$("#signatureState").textContent=i.signed?'checkpoint firmado':'checkpoint verificable · firma pendiente';$("#merkleRoot").textContent=i.merkle_root_sha256||'Aún no generado en esta copia local'}catch(e){$("#snapshotDate").textContent='Datos al desplegar';$("#snapshotRecords").textContent='pipeline preparado';$("#changeCount").textContent='—';$("#treeSize").textContent='—'}}
render();renderSignals();loadStatus();
